// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRdiVr1Bh2s2Ncsbfoov_mdM8nVBlt4as',
    appId: '1:971530207266:web:ea485170b6622c0c310a7b',
    messagingSenderId: '971530207266',
    projectId: 'timemanagement-ase456-hw8',
    authDomain: 'timemanagement-ase456-hw8.firebaseapp.com',
    storageBucket: 'timemanagement-ase456-hw8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQl407OcpHqXDWpYbyrF-GGW8muVOib_4',
    appId: '1:971530207266:android:26795a963ddb8825310a7b',
    messagingSenderId: '971530207266',
    projectId: 'timemanagement-ase456-hw8',
    storageBucket: 'timemanagement-ase456-hw8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHYx8pnut5buzVIL8ZcO_jRgE4RjVzq24',
    appId: '1:971530207266:ios:d0744f805f317c72310a7b',
    messagingSenderId: '971530207266',
    projectId: 'timemanagement-ase456-hw8',
    storageBucket: 'timemanagement-ase456-hw8.appspot.com',
    iosBundleId: 'com.example.ase456Hw8IndividualProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHYx8pnut5buzVIL8ZcO_jRgE4RjVzq24',
    appId: '1:971530207266:ios:e2189e66e3ecf1c4310a7b',
    messagingSenderId: '971530207266',
    projectId: 'timemanagement-ase456-hw8',
    storageBucket: 'timemanagement-ase456-hw8.appspot.com',
    iosBundleId: 'com.example.ase456Hw8IndividualProject.RunnerTests',
  );
}
